### PR TITLE
without multipart unable to upload files

### PR DESCRIPTION
**Pull request by dmkdev**

### CODE REVIEW

**Comment by antonkomarev** [comment]
Thank you for the PR, @dmkdev!

Could you provide test for this use case? Or at least describe how it works without your PR and how it will work with it.

**Comment by dmkdev** [comment]
Hi, @a-komarev ! My use case:
```javascript
$mutipart = [[
            'name' => 'files',
            'filename' => 'filename',
            'contents' => fopen('/path/to/file', 'r'),
        ]];
        
$response = $this->youtrack->post('/issue/' . $issueId . '/attachment', [], [
           'multipart' => $mutipart
]);
```
WIthout PR unable to set options 'multipart'

**Comment by antonkomarev** [comment]
I'm merging it, but its not ready for release. Will make some more changes later.

**Comment by antonkomarev** [comment]
@dmkdev I've added you to contributors list, but cannot place your avatar, because default GitHub avatars are not sizing (rendering 420x420 by default) and it breaks markup.

Release 6.1.0 published. Thank you for the feature contribution.

**Pull request merged**
